insolar/observer

- .github/workflows/pr.yml
- Makefile
- component/storer_test.go
- internal/app/api/handlers_test.go
- internal/app/observer/postgres/deposit_test.go
- internal/app/observer/postgres/main_test.go
- internal/app/observer/postgres/network_stats_test.go
- internal/app/observer/postgres/supply_stats_test.go
Isolated tests using setup db, fixed other tests to find particular transactions/notifications in order to run in parallel or with the count.
> PENV-252: fix non atomic tests

- .github/workflows/pr.yml
- Makefile
- internal/app/observer/postgres/binance_stats_test.go
- internal/app/observer/postgres/coin_market_cap_stats_test.go
- internal/app/observer/postgres/deposit_test.go
- internal/app/observer/postgres/main_test.go
- internal/app/observer/postgres/network_stats_test.go
- internal/app/observer/postgres/supply_stats_test.go
- internal/testutils/db.go
2020-05-21T02:14:33.6691358Z race: limit on 8128 simultaneously alive goroutines is exceeded, dying, trying to decrease count, increase timeout, switched from pr to nightly mode.
> PENV-252: decrease count, race detector goroutines limit is reached

- README.md
- scripts/monitor/prometheus/prometheus.yaml
Manual for starting monitoring  and tips for graph
task: https://insolar.atlassian.net/browse/MN-397
> MN-397: add instruction for monitoring

- connectivity/credentials.go
- connectivity/credentials_test.go
**- What I did**
I have started to correctly calculate a time to refresh JWT.
> MN-491: fix JWT refreshing

- internal/app/observer/collecting/transactions.go
- internal/app/observer/collecting/transactions_test.go
- internal/models/models.go
- scripts/migrations/9_alter_transaction_type.up.sql
added transaction start collector for account.transferToDeposit
added transaction result collecting
added allocation saga call fail
added migration
added tests
tested on mainnet functests
> mn-614 collector for account.transferToDeposit

- component/storer_test.go
- internal/app/observer/deposit.go
- internal/app/observer/postgres/deposit_test.go
- internal/models/models.go
- scripts/migrations/9_deposits_vesting_type.up.sql
- Modified the migration script where was added the new column _vesting_type_  to the _deposits_ table
- Extended _Deposit_ model
> MN-585: deposit vesting types

- .github/workflows/build.yaml
Build docker images on push to master and push it to docker.hub as :latest.
> OPS-326: build :latest on push to master

- component/fetcher.go
Change log level from err to warn when get empty response (getPulse)
https://insolar.atlassian.net/browse/PENV-531
> MN-531: change log level

- scripts/monitor/docker-compose.yml
- scripts/monitor/grafana/dashboards/observer.json
Add metrics on dashboard. When client is deprecated
> MN-570: add metrics version

- internal/app/observer/collecting/transactions.go
- internal/app/observer/collecting/transactions_test.go
fixed deserializing of new parameter
> penv-514 fix deserialize new param

- README.md
**What has changed:** Node updating instructions.
**How:** Added a draft of updating instructions to the README.md in the repo root. 
**Why:** Need to inform Node users on how to update their Node instance, as we're implementing a version check mechanism between Insolar Platform along with Insolar MainNet and client using them, and as we're also implementing operational restrictions as well.
> create initial draft of the Future Node updates section

- cmd/stats-collector/main.go
- internal/app/observer/postgres/supply_stats.go
- internal/app/observer/postgres/supply_stats_test.go
Total supply now is calculated based on account balances and deposits balances
> MN-681: total supply calculation

- cmd/binance-collector/main.go
- cmd/coin-market-cap-collector/main.go
- cmd/stats-collector/main.go
- internal/integration/cli_test.go
removed "-" from env prefixes
STATS-COLLECTOR > STATSCOLLECTOR
BINANCE-COLLECTOR > BINANCECOLLECTOR
COIN-MARKET-CAP-COLLECTOR > COINMARKETCAPCOLLECTOR
> penv-514 removed "-" from env prefixes

- internal/app/observer/collecting/transactions.go
> Revert "MN-761: use TransferToDeposit request reference as txID"

- cmd/stats-collector/main.go
- internal/app/observer/postgres/supply_stats.go
- internal/app/observer/postgres/supply_stats_test.go
Total supply now is calculated based on account balances and deposits balances
> MN-681: total supply calc

- cmd/coin-market-cap-collector/main.go
- configuration/api.go
- configuration/api_extended.go
- configuration/testdata/observerapi.yaml
- internal/app/api/services/generated.go
- internal/app/api/services/handlers.go
- internal/app/api/services/handlers_test.go
- internal/app/observer/postgres/coin_market_cap_stats_test.go
- internal/models/models.go
- scripts/migrations/10_remove_column_cmc.up.sql
what I did:
- removed circulation supply
> MN-680: removed circulation supply

- component/storer.go
- go.mod
- go.sum
- internal/pkg/cycle/until.go
- vendor/github.com/insolar/insolar/configuration/exporter.go
- vendor/modules.txt
what I did:
- move panic to the until connection error
> MN-399: move panic to the until connection error

- internal/app/observer/grpc/pulse.go
- internal/app/observer/postgres/migration_address.go
- internal/pkg/cycle/until.go
**-Wha I did:**
I have split a function into two related but different.
> PENV-643: separate an UntilError from an UntilConnectionError

- .github/workflows/e2e.yaml
- deploy/autotests-pod/kustomization.yaml
- deploy/mainnet/kustomization.yaml
**- What I did**
Added GHA workflow which executes e2e [go-autotests](https://github.com/insolar/go-autotests) on current git commit.
**- How I did it**
**- How to verify it**
Run e2e workflow (see [checks](https://github.com/insolar/observer/actions?query=workflow%3Ae2e))
**- Description for the changelog**
> OPS-354 mainnet e2e autotests

- go.sum
- internal/pkg/cycle/until.go
Fix panic in the UntilConnectionError function.
> PENV-651: fix panic on DB EOF error

- internal/app/api/generated.go
- internal/app/api/generated_extended.go
- internal/app/api/mappers.go
- internal/app/observer/collecting/transactions.go
- internal/app/observer/collecting/transactions_test.go
- internal/models/models.go
Added collector cases to gather `burn` transactions
> MN-798: add cases to collect burn transactions

- .github/workflows/pr.yml
send notification to slack if workflow job fails
> OPS-385 send notification to slack if workflow job fails

- go.mod
- go.sum
- internal/app/observer/collecting/deposit_test.go
- internal/app/observer/collecting/transactions.go
what I did:
- update mainnet version
> MN-806: update mainnet version

- internal/app/observer/collecting/burned_balance.go
- scripts/migrations/12_burn_tx_type.up.sql
what I did:
-  add transaction type
- removed the error output for all other types of records, prototype checking is lower in the code
> MN-825: add transaction type

- internal/app/observer/postgres/burned_balance.go
what I did:
- fix update amend
> MN-825: fix update amend

- .github/workflows/pr.yml
> NOISSUE disable scheduled jobs
